name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        continue-on-error: true
        run: |
          echo hello | grep no 
      - name: to stuff
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.event.label.name }}
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo $PR_NUMBER
          echo world
      - name: Dump GitHub ontext
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
